import type { Metadata } from "next";
import "./globals.css";
import QueryClient from "@/components/QueryClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryClient>
        <body className='antialiased'>
          <div className="flex flex-col justify-center items-center bg-grid-paper w-screen h-screen">
            {children}
          </div>
        </body>
      </QueryClient>
    </html>
  );
}
